language: python
env:
  matrix:
  - TEST_PYCRYPTO="true" TEST_GMPY="true"
  - TEST_PYCRYPTO="false" TEST_GMPY="true"
  - TEST_PYCRYPTO="true" TEST_GMPY="false"
  - TEST_PYCRYPTO="false" TEST_GMPY="false"
python:
  - 3.3
  - 3.4
matrix:
  include:
    - python: 3.4
    - python: 3.3
    - python: "pypy3"
      env: TEST_GMPY="false"
  allow_failures:
    - python: "pypy3"
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-crypto
  - sudo apt-get install -qq libgmp-dev libmpfr-dev
  - sudo apt-get install -qq libgmp3-dev libgmp3c2 libmpfr4 libmpc-dev libmpc2
  # Install gmpy2 dependencies
  - if [[ $TEST_GMPY == "true" ]]; then
      wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz;
      tar xzvf mpc-1.0.2.tar.gz;
      cd mpc-1.0.2;
      ./configure;
      make;
      sudo make install;
      cd ..;
      pip install gmpy2==2.0.3;
    fi
  # End install gmpy2 dependencies
  - if [[ $TEST_PYCRYPTO ]]; then
      pip install pycrypto==2.6.1;
    fi
install:
  - pip install nose
# command to run tests
script:  nosetests