# After changing this file, check it on:
#   http://lint.travis-ci.org/
sudo: false
language: python
env:
  - TEST_PYCRYPTO="true" TEST_GMPY="true"
  - TEST_PYCRYPTO="false" TEST_GMPY="true"

# Note travis times out with the following:
#  - TEST_PYCRYPTO="true" TEST_GMPY="false"

# In order to test with and without some libraries, we explicitly
# install deps instead of installing from the requirements file

matrix:
  include:
    - python: 3.3
    - python: 3.4
    - python: 3.5
      env:
        - TEST_PYCRYPTO=1
    - python: 3.6

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev

before_install:
  - export PYTHONFAULTHANDLER=1
  - export PATH=/usr/lib/ccache:$PATH
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  # Install gmpy2 dependencies
  - mkdir -p $HOME/.local
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
  - tar xzvf mpc-1.0.3.tar.gz
  - pushd mpc-1.0.3
  - ./configure --prefix=$HOME/.local
  - make
  - make install
  - popd
  - export CPATH=$HOME/.local/include
  - export LIBRARY_PATH=$HOME/.local/lib
  - export LD_LIBRARY_PATH=$HOME/.local/lib
  - travis_retry pip install gmpy2
  - if [ "${TESTMODE}" == "full" ]; then pip install coverage; fi
  - travis_retry pip install -U pip setuptools
  - if [ "${USE_WHEEL}" == "1" ]; then pip install wheel; fi
  - if [ "${TEST_PYCRYPTO}" == "1" ]; then pip install pycrypto>=2.6.1; fi
  - travis_retry pip install nose numpy click

script: nosetests -v
