language: python
env:
  matrix:
  - DEPS="true"
  - DEPS="false"
python:
  - 3.3
  - 3.4
matrix:
  include:
    - python: 3.4
      env:
        - TEST_GMPY="true"
    - python: 3.3
      env:
        - TEST_GMPY="true"
    - python: "pypy3"
      env:
        - TEST_GMPY="false"
  allow_failures:
    - python: "pypy3"
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-crypto
  - sudo apt-get install -qq libgmp-dev libmpfr-dev
  - sudo apt-get install -qq libgmp3-dev libgmp3c2 libmpfr4 libmpc-dev libmpc2
  # Install gmpy2 dependencies
  - if [[ $TEST_GMPY == "true" ]]; then
      wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz;
      tar xzvf mpc-1.0.2.tar.gz;
      cd mpc-1.0.2;
      ./configure;
      make;
      sudo make install;
      cd ..;
    fi
  # End install gmpy2 dependencies

install:
  - if [[ $DEPS == "true" ]]; then pip install  -r requirements.txt; fi
# command to run tests
script:  nosetests