language: python
python:
  - "3.4"
  - "3.3"
  - "pypy3"
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-crypto
  - sudo apt-get install -qq libgmp-dev libmpfr-dev
  - sudo apt-get install -qq libgmp3-dev libgmp3c2 libmpfr4 libmpc-dev libmpc2
  # Install gmpy2 dependencies
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
  - tar xzvf mpc-1.0.2.tar.gz
  - cd mpc-1.0.2
  - ./configure
  - make
  - sudo make install
  - cd ..
  # End install gmpy2 dependencies
  pip install gmpy2
install: pip install -r requirements.txt
# command to run tests
script:  nosetests